#  strval.awk Copyright (c) 1993-2018, David A. Clunie DBA PixelMed Publishing. All rights reserved.
# create C++ headers from string values template 

# can set these values on the command line:
#


NR==1	{
	print "# Automatically generated from template - EDITS WILL BE LOST"
	print ""
	print "# Generated by strval.awk with options " role " " outname
	print ""



	mode=""
}

/^[ 	]*StringValues/ {
	name=""
	if (match($0,"StringValues=\"[^\"]*\""))
		name=substr($0,RSTART+length("StringValues=\""),
			RLENGTH-length("StringValues=\"")-1);
	mode="values"
	n = 0

		
		print "StringValueTable_" name " = {"
}	
$0 !~ /(.*[{}])|(^[ 	]*$)|(^[ 	]*#)/ {
n++;
	if (mode == "values")
	{
		valueline=$0
		if (match(valueline,"[^ 	=,][^=,]*")) 
		{
			code=substr(valueline,RSTART,RLENGTH)
			# remove trailing spaces ...
			if (match(code,"[ 	]*$")) 
			{
				sub("[ 	]*$","",code);
				#code=substr(code,0,RSTART-1)
			}
			valueline=substr(valueline,RSTART+RLENGTH)
			if (code == "***EMPTYVALUE***")
				code=""
		}
		else 
		{
			print "Line " FNR \
				": warning in value line - no code <" \
				valueline ">" >"/dev/tty"
			code=""

		}

		if (match(valueline,"[ 	]*=[ 	]*")) 
		{
			meaning=substr(valueline,RSTART+RLENGTH)

			if (match(meaning,"[ 	]*,*[ 	]*$"))
				meaning=substr(meaning,0,RSTART-1)
		}
		else 
			meaning=""
		if (n == 1)
			print "\t\"" code "\" : \"" meaning "\""
		else
			print "\t,\"" code "\" : \"" meaning "\""
	}
	else 
		print "Line " FNR ": error - no group name" >"/dev/tty"

}

/^[ 	]*}/ {
	if (mode == "values") 
	{
		print "}"
		print ""
		
	}
	n = 0
	mode=""
}
