# Automatically generated from template - EDITS WILL BE LOST

# Generated by tagval.awk with options  

from numpy import *
def TagValueDescription_NMFrameIncrementPointerValues(group:uint16,element:uint16)->str:
	ost = ""
	value=(uint32(group)<<16)|element
	if value == (uint32(0x0054)<<16)|0x0010 :
		ost += "Energy Window Vector" 
		return ost
	elif value == (uint32(0x0054)<<16)|0x0020 :
		ost += "Detector Vector" 
		return ost
	elif value == (uint32(0x0054)<<16)|0x0030 :
		ost += "Phase Vector" 
		return ost
	elif value == (uint32(0x0054)<<16)|0x0050 :
		ost += "Rotation Vector" 
		return ost
	elif value == (uint32(0x0054)<<16)|0x0060 :
		ost += "RR Interval Vector" 
		return ost
	elif value == (uint32(0x0054)<<16)|0x0070 :
		ost += "Time Slot Vector" 
		return ost
	elif value == (uint32(0x0054)<<16)|0x0080 :
		ost += "Slice Vector" 
		return ost
	elif value == (uint32(0x0054)<<16)|0x0090 :
		ost += "Angular View Vector" 
		return ost
	elif value == (uint32(0x0054)<<16)|0x0100 :
		ost += "Time Slice Vector" 
		return ost
	else:
		return ""

def TagValueDescription_XRayFrameIncrementPointerValues(group:uint16,element:uint16)->str:
	ost = ""
	value=(uint32(group)<<16)|element
	if value == (uint32(0x0018)<<16)|0x1063 :
		ost += "Frame Time" 
		return ost
	elif value == (uint32(0x0018)<<16)|0x1065 :
		ost += "Frame Time Vector" 
		return ost
	else:
		return ""

def TagValueDescription_FrameIncrementPointerIsEnergyWindowVector(group:uint16,element:uint16)->str:
	ost = ""
	value=(uint32(group)<<16)|element
	if value == (uint32(0x0054)<<16)|0x0010 :
		ost += "Energy Window Vector" 
		return ost
	else:
		return ""

def TagValueDescription_FrameIncrementPointerIsDetectorVector(group:uint16,element:uint16)->str:
	ost = ""
	value=(uint32(group)<<16)|element
	if value == (uint32(0x0054)<<16)|0x0020 :
		ost += "Detector Vector" 
		return ost
	else:
		return ""

def TagValueDescription_FrameIncrementPointerIsPhaseVector(group:uint16,element:uint16)->str:
	ost = ""
	value=(uint32(group)<<16)|element
	if value == (uint32(0x0054)<<16)|0x0030 :
		ost += "Phase Vector" 
		return ost
	else:
		return ""

def TagValueDescription_FrameIncrementPointerIsRotationVector(group:uint16,element:uint16)->str:
	ost = ""
	value=(uint32(group)<<16)|element
	if value == (uint32(0x0054)<<16)|0x0050 :
		ost += "Rotation Vector" 
		return ost
	else:
		return ""

def TagValueDescription_FrameIncrementPointerIsRRIntervalVector(group:uint16,element:uint16)->str:
	ost = ""
	value=(uint32(group)<<16)|element
	if value == (uint32(0x0054)<<16)|0x0060 :
		ost += "RR Interval Vector" 
		return ost
	else:
		return ""

def TagValueDescription_FrameIncrementPointerIsTimeSlotVector(group:uint16,element:uint16)->str:
	ost = ""
	value=(uint32(group)<<16)|element
	if value == (uint32(0x0054)<<16)|0x0070 :
		ost += "Time Slot Vector" 
		return ost
	else:
		return ""

def TagValueDescription_FrameIncrementPointerIsSliceVector(group:uint16,element:uint16)->str:
	ost = ""
	value=(uint32(group)<<16)|element
	if value == (uint32(0x0054)<<16)|0x0080 :
		ost += "Slice Vector" 
		return ost
	else:
		return ""

def TagValueDescription_FrameIncrementPointerIsAngularViewVector(group:uint16,element:uint16)->str:
	ost = ""
	value=(uint32(group)<<16)|element
	if value == (uint32(0x0054)<<16)|0x0090 :
		ost += "Angular View Vector" 
		return ost
	else:
		return ""

def TagValueDescription_FrameIncrementPointerIsTimeSliceVector(group:uint16,element:uint16)->str:
	ost = ""
	value=(uint32(group)<<16)|element
	if value == (uint32(0x0054)<<16)|0x0100 :
		ost += "Time Slice Vector" 
		return ost
	else:
		return ""

def TagValueDescription_XAFrameDimensionPointerValues(group:uint16,element:uint16)->str:
	ost = ""
	value=(uint32(group)<<16)|element
	if value == (uint32(0x0018)<<16)|0x1063 :
		ost += "Frame Time" 
		return ost
	elif value == (uint32(0x0018)<<16)|0x1065 :
		ost += "Frame Time Vector" 
		return ost
	elif value == (uint32(0x0018)<<16)|0x1520 :
		ost += "Positioner Primary Angle Increment" 
		return ost
	elif value == (uint32(0x0018)<<16)|0x1521 :
		ost += "Positioner Secondary Angle Increment" 
		return ost
	elif value == (uint32(0x0018)<<16)|0x1135 :
		ost += "Table Vertical Increment" 
		return ost
	elif value == (uint32(0x0018)<<16)|0x1137 :
		ost += "Table Longitudinal Increment" 
		return ost
	elif value == (uint32(0x0018)<<16)|0x1136 :
		ost += "Table Lateral Increment" 
		return ost
	elif value == (uint32(0x0018)<<16)|0x2002 :
		ost += "Frame Label Vector" 
		return ost
	else:
		return ""

def TagValueDescription_QTUSDimensionOrganization3DDimensionIndexPointerValues(group:uint16,element:uint16)->str:
	ost = ""
	value=(uint32(group)<<16)|element
	if value == (uint32(0x0020)<<16)|0x930D :
		ost += "Temporal Position Time Offset" 
		return ost
	elif value == (uint32(0x0020)<<16)|0x9301 :
		ost += "Image Position (Volume)" 
		return ost
	elif value == (uint32(0x0018)<<16)|0x9808 :
		ost += "Data Type" 
		return ost
	else:
		return ""

def TagValueDescription_QTUSDimensionOrganization3DFunctionalGroupPointerValues(group:uint16,element:uint16)->str:
	ost = ""
	value=(uint32(group)<<16)|element
	if value == (uint32(0x0020)<<16)|0x9310 :
		ost += "Temporal Position Sequence" 
		return ost
	elif value == (uint32(0x0020)<<16)|0x930E :
		ost += "Plane Position (Volume) Sequence" 
		return ost
	elif value == (uint32(0x0018)<<16)|0x9807 :
		ost += "Image Data Type Sequence" 
		return ost
	else:
		return ""

